import os
from dotenv import load_dotenv
load_dotenv()

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
CHAT_ID = os.getenv("CHAT_ID")

DERIV_APP_ID = os.getenv("DERIV_APP_ID", "1089")
DERIV_TOKEN = os.getenv("DERIV_TOKEN")
DERIV_DEMO = True

ACTIVE_SYMBOL = "V75"
STAKE_AMOUNT = 1.0
MAX_STAKE = 10.0
DURATION = 5
DURATION_UNIT = "t"
MAX_DAILY_LOSS = 0.10
MAX_DAILY_TRADES = 50
RISK_PER_TRADE = 0.02

AI_MODE = "AUTO"
MIN_CONFIDENCE = 0.65
CANDLE_TF = 60
OBI_THRESHOLD = 0.55
MAX_CONSECUTIVE_LOSS = 3